#!/usr/bin/env python3
"""Test-only stand-in for the third-party APIs InsightsLM's workflows call. Never part of the template.

  POST /v1/chat/completions                    OpenAI chat: one JSON object satisfying every structured-output
                                               schema the workflows use; a podcast script when asked for one
  POST /v1/embeddings                          OpenAI embeddings: deterministic 1536-dimension vectors
  POST /v1/audio/transcriptions                OpenAI transcription
  POST /v1beta/models/<model>:generateContent  Gemini text-to-speech: half a second of 24 kHz PCM
  GET  /reader/<url>                           Jina reader: a page's title and content

Every request is logged with its path only. Listens on [::]:8000 (IPv4 too).
"""
import base64
import hashlib
import json
import socket
import struct
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

MARKER = "mock-ai-answer"


def chat_content(body: dict) -> str:
    text = json.dumps(body.get("messages", []))
    if "podcast" in text.lower():
        return "Speaker 1: Welcome to the probe podcast.\nSpeaker 2: It was generated by the stand-in model."
    # n8n's Structured Output Parser wraps every schema in {"output": ...}; one object fits all three workflows'
    # schemas (chat answer, source title and summary, notebook details).
    return json.dumps({"output": {
        "output": [{"text": f"{MARKER}: the sources say the railway probe works.", "citations": []}],
        "title": f"Probe title {MARKER}",
        "summary": f"Probe summary {MARKER}",
        "notebook_icon": "📘",
        "background_color": "blue",
        "example_questions": ["What does the probe say?", "Who wrote it?"],
    }})


def embedding(text: str) -> list:
    seed = hashlib.sha256(text.encode()).digest()
    return [((seed[i % 32] + i) % 17 - 8) / 8.0 for i in range(1536)]


class Handler(BaseHTTPRequestHandler):
    def log_message(self, fmt, *args):
        print(f"mock-ai {self.command} {self.path.split('?')[0]}", flush=True)

    def send_json(self, obj, status=200):
        data = json.dumps(obj).encode()
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(data)))
        self.end_headers()
        self.wfile.write(data)

    def body(self):
        n = int(self.headers.get("Content-Length") or 0)
        raw = self.rfile.read(n) if n else b""
        ctype = self.headers.get("Content-Type", "")
        if "json" in ctype:
            try:
                return json.loads(raw or b"{}")
            except ValueError:
                return {}
        return {"_raw": len(raw)}

    def do_GET(self):
        if self.path.startswith("/reader/"):
            url = self.path[len("/reader/"):]
            self.send_json({"code": 200, "data": {"title": "Probe page", "url": url, "content": f"Probe page content about railways. {MARKER}"}})
        elif self.path == "/health":
            self.send_json({"ok": True})
        else:
            self.send_json({"error": "not found"}, 404)

    def do_POST(self):
        path = self.path.split("?")[0]
        body = self.body()
        if path.endswith("/chat/completions"):
            content = chat_content(body)
            if body.get("stream"):
                self.send_response(200)
                self.send_header("Content-Type", "text/event-stream")
                self.end_headers()
                chunk = {"id": "c1", "object": "chat.completion.chunk", "model": body.get("model", "mock"),
                         "choices": [{"index": 0, "delta": {"role": "assistant", "content": content}, "finish_reason": None}]}
                self.wfile.write(f"data: {json.dumps(chunk)}\n\n".encode())
                done = {"id": "c1", "object": "chat.completion.chunk", "model": body.get("model", "mock"),
                        "choices": [{"index": 0, "delta": {}, "finish_reason": "stop"}]}
                self.wfile.write(f"data: {json.dumps(done)}\n\ndata: [DONE]\n\n".encode())
                return
            self.send_json({"id": "c1", "object": "chat.completion", "created": 0, "model": body.get("model", "mock"),
                            "choices": [{"index": 0, "message": {"role": "assistant", "content": content}, "finish_reason": "stop"}],
                            "usage": {"prompt_tokens": 1, "completion_tokens": 1, "total_tokens": 2}})
        elif path.endswith("/embeddings"):
            inputs = body.get("input", [])
            inputs = inputs if isinstance(inputs, list) else [inputs]
            # The OpenAI SDK asks for base64 (little-endian float32) and decodes it itself.
            b64 = body.get("encoding_format") == "base64"
            encode = (lambda v: base64.b64encode(struct.pack(f"<{len(v)}f", *v)).decode()) if b64 else (lambda v: v)
            self.send_json({"object": "list", "model": body.get("model", "mock"),
                            "data": [{"object": "embedding", "index": i, "embedding": encode(embedding(str(t)))} for i, t in enumerate(inputs)],
                            "usage": {"prompt_tokens": 1, "total_tokens": 1}})
        elif path.endswith("/audio/transcriptions"):
            self.send_json({"text": f"Transcribed probe audio. {MARKER}"})
        elif ":generateContent" in path:
            pcm = b"\x00\x00" * 12000
            self.send_json({"responseId": "probe-audio", "candidates": [{"content": {"parts": [
                {"inlineData": {"mimeType": "audio/L16;codec=pcm;rate=24000", "data": base64.b64encode(pcm).decode()}}]}}]})
        else:
            self.send_json({"error": "not found"}, 404)


class Server(ThreadingHTTPServer):
    address_family = socket.AF_INET6

    def server_bind(self):
        self.socket.setsockopt(socket.IPPROTO_IPV6, socket.IPV6_V6ONLY, 0)
        super().server_bind()


if __name__ == "__main__":
    Server(("::", 8000), Handler).serve_forever()
